/* Generated Fix Gateway message codec */
package com.swiftalgo.ms.codecs.fix50sp2;

import uk.co.real_logic.artio.dictionary.CharArrayMap;
import uk.co.real_logic.artio.dictionary.CharArrayWrapper;
import org.agrona.collections.IntHashSet;
import java.util.Map;
import java.util.HashMap;
import uk.co.real_logic.artio.builder.StringRepresentable;
public enum MatchType implements StringRepresentable
{
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME("A1"),
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES("A2"),
    ACT_ACCEPTED_TRADE("M3"),
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME("A3"),
    ACT_DEFAULT_TRADE("M4"),
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES("A4"),
    ACT_DEFAULT_AFTER_M2("M5"),
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADETYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME("A5"),
    ACT_M6_MATCH("M6"),
    COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST_ACCEPTS_PAIR_OFFS("AQ"),
    SUMMARIZED_MATCH_USING_A1_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIED("S1"),
    SUMMARIZED_MATCH_USING_A2_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED("S2"),
    SUMMARIZED_MATCH_USING_A3_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED("S3"),
    SUMMARIZED_MATCH_USING_A4_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED("S4"),
    SUMMARIZED_MATCH_USING_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED("S5"),
    EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_MINUS_BADGES_AND_TIMES_ACT_M1_MATCH("M1"),
    SUMMARIZED_MATCH_MINUS_BADGES_AND_TIMES_ACT_M2_MATCH("M2"),
    OCS_LOCKED_IN_NON_ACT("MT"),
    ONE_PARTY_TRADE_REPORT("1"),
    TWO_PARTY_TRADE_REPORT("2"),
    CONFIRMED_TRADE_REPORT("3"),
    AUTO_MATCH("4"),
    CROSS_AUCTION("5"),
    COUNTER_ORDER_SELECTION("6"),
    CALL_AUCTION("7"),
    ISSUING_BUY_BACK_AUCTION("8"),
    NULL_VAL(""),
    ARTIO_UNKNOWN("");

    private final String representation;

    MatchType(final String representation)
    {
         this.representation = representation;
    }

    public final String representation() { return representation; }

    private static final CharArrayMap<MatchType> charMap;
    static
    {
        final Map<String, MatchType> stringMap = new HashMap<>();
        stringMap.put("A1", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME);
        stringMap.put("A2", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES);
        stringMap.put("M3", ACT_ACCEPTED_TRADE);
        stringMap.put("A3", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME);
        stringMap.put("M4", ACT_DEFAULT_TRADE);
        stringMap.put("A4", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES);
        stringMap.put("M5", ACT_DEFAULT_AFTER_M2);
        stringMap.put("A5", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADETYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME);
        stringMap.put("M6", ACT_M6_MATCH);
        stringMap.put("AQ", COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST_ACCEPTS_PAIR_OFFS);
        stringMap.put("S1", SUMMARIZED_MATCH_USING_A1_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIED);
        stringMap.put("S2", SUMMARIZED_MATCH_USING_A2_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED);
        stringMap.put("S3", SUMMARIZED_MATCH_USING_A3_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED);
        stringMap.put("S4", SUMMARIZED_MATCH_USING_A4_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED);
        stringMap.put("S5", SUMMARIZED_MATCH_USING_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED);
        stringMap.put("M1", EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_MINUS_BADGES_AND_TIMES_ACT_M1_MATCH);
        stringMap.put("M2", SUMMARIZED_MATCH_MINUS_BADGES_AND_TIMES_ACT_M2_MATCH);
        stringMap.put("MT", OCS_LOCKED_IN_NON_ACT);
        stringMap.put("1", ONE_PARTY_TRADE_REPORT);
        stringMap.put("2", TWO_PARTY_TRADE_REPORT);
        stringMap.put("3", CONFIRMED_TRADE_REPORT);
        stringMap.put("4", AUTO_MATCH);
        stringMap.put("5", CROSS_AUCTION);
        stringMap.put("6", COUNTER_ORDER_SELECTION);
        stringMap.put("7", CALL_AUCTION);
        stringMap.put("8", ISSUING_BUY_BACK_AUCTION);
        charMap = new CharArrayMap<>(stringMap);
    }

    public static MatchType decode(final CharArrayWrapper key)
    {
        final MatchType value = charMap.get(key);
        if (value == null)
        {
            return ARTIO_UNKNOWN;
        }
        return value;
    }
    public static boolean isValid(final CharArrayWrapper key)
    {
        return charMap.containsKey(key);
    }
    public static MatchType decode(final String representation)
    {
        switch(representation)
        {
        case "A1": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME;
        case "A2": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES;
        case "M3": return ACT_ACCEPTED_TRADE;
        case "A3": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME;
        case "M4": return ACT_DEFAULT_TRADE;
        case "A4": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES;
        case "M5": return ACT_DEFAULT_AFTER_M2;
        case "A5": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADETYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME;
        case "M6": return ACT_M6_MATCH;
        case "AQ": return COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST_ACCEPTS_PAIR_OFFS;
        case "S1": return SUMMARIZED_MATCH_USING_A1_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIED;
        case "S2": return SUMMARIZED_MATCH_USING_A2_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED;
        case "S3": return SUMMARIZED_MATCH_USING_A3_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED;
        case "S4": return SUMMARIZED_MATCH_USING_A4_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED;
        case "S5": return SUMMARIZED_MATCH_USING_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED;
        case "M1": return EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_MINUS_BADGES_AND_TIMES_ACT_M1_MATCH;
        case "M2": return SUMMARIZED_MATCH_MINUS_BADGES_AND_TIMES_ACT_M2_MATCH;
        case "MT": return OCS_LOCKED_IN_NON_ACT;
        case "1": return ONE_PARTY_TRADE_REPORT;
        case "2": return TWO_PARTY_TRADE_REPORT;
        case "3": return CONFIRMED_TRADE_REPORT;
        case "4": return AUTO_MATCH;
        case "5": return CROSS_AUCTION;
        case "6": return COUNTER_ORDER_SELECTION;
        case "7": return CALL_AUCTION;
        case "8": return ISSUING_BUY_BACK_AUCTION;
        default:
            return ARTIO_UNKNOWN;
        }
    }
}
