/* Generated Fix Gateway message codec */
package com.swiftalgo.ms.codecs.fix50sp2.decoder;

import org.agrona.AsciiNumberFormatException;
import org.agrona.MutableDirectBuffer;
import org.agrona.AsciiSequenceView;
import static uk.co.real_logic.artio.dictionary.generation.CodecUtil.*;
import static uk.co.real_logic.artio.dictionary.SessionConstants.*;
import uk.co.real_logic.artio.builder.Decoder;
import uk.co.real_logic.artio.fields.DecimalFloat;
import uk.co.real_logic.artio.util.MutableAsciiBuffer;
import uk.co.real_logic.artio.util.AsciiBuffer;
import uk.co.real_logic.artio.fields.LocalMktDateEncoder;
import uk.co.real_logic.artio.fields.UtcTimestampEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import uk.co.real_logic.artio.dictionary.CharArraySet;
import org.agrona.collections.IntHashSet;
import org.agrona.collections.IntHashSet.IntIterator;
import uk.co.real_logic.artio.EncodingException;
import uk.co.real_logic.artio.dictionary.CharArrayWrapper;
import uk.co.real_logic.artio.builder.Encoder;
import uk.co.real_logic.artio.builder.CommonDecoderImpl;
import static java.nio.charset.StandardCharsets.US_ASCII;
import static uk.co.real_logic.artio.builder.Validation.CODEC_VALIDATION_ENABLED;
import static uk.co.real_logic.artio.builder.RejectUnknownField.CODEC_REJECT_UNKNOWN_FIELD_ENABLED;
import static uk.co.real_logic.artio.builder.RejectUnknownEnumValue.CODEC_REJECT_UNKNOWN_ENUM_VALUE_ENABLED;
import com.swiftalgo.ms.codecs.fix50sp2.*;
import com.swiftalgo.ms.codecs.fix50sp2.builder.InstrumentLegEncoder;
import com.swiftalgo.ms.codecs.fix50sp2.builder.LegSecAltIDGrpEncoder;
import static com.swiftalgo.ms.codecs.fix50sp2.builder.LegSecAltIDGrpEncoder.LegSecurityAltIDGroupEncoder;

public interface InstrumentLegDecoder  extends LegSecAltIDGrpDecoder
{

    public char[] legSymbol();
    public boolean hasLegSymbol();
    public int legSymbolLength();
    public void legSymbol(AsciiSequenceView view);
    public char[] legSymbolSfx();
    public boolean hasLegSymbolSfx();
    public int legSymbolSfxLength();
    public void legSymbolSfx(AsciiSequenceView view);
    public char[] legSecurityID();
    public boolean hasLegSecurityID();
    public int legSecurityIDLength();
    public void legSecurityID(AsciiSequenceView view);
    public char[] legSecurityIDSource();
    public boolean hasLegSecurityIDSource();
    public int legSecurityIDSourceLength();
    public void legSecurityIDSource(AsciiSequenceView view);
    public int legProduct();
    public boolean hasLegProduct();
    public char[] legCFICode();
    public boolean hasLegCFICode();
    public int legCFICodeLength();
    public void legCFICode(AsciiSequenceView view);
    public char[] legSecurityType();
    public boolean hasLegSecurityType();
    public int legSecurityTypeLength();
    public void legSecurityType(AsciiSequenceView view);
    public char[] legSecuritySubType();
    public boolean hasLegSecuritySubType();
    public int legSecuritySubTypeLength();
    public void legSecuritySubType(AsciiSequenceView view);
    public byte[] legMaturityMonthYear();
    public boolean hasLegMaturityMonthYear();
    public int legMaturityMonthYearLength();
    public void legMaturityMonthYear(AsciiSequenceView view);
    public byte[] legMaturityDate();
    public boolean hasLegMaturityDate();
    public int legMaturityDateLength();
    public void legMaturityDate(AsciiSequenceView view);
    public byte[] legMaturityTime();
    public boolean hasLegMaturityTime();
    public int legMaturityTimeLength();
    public void legMaturityTime(AsciiSequenceView view);
    public byte[] legCouponPaymentDate();
    public boolean hasLegCouponPaymentDate();
    public int legCouponPaymentDateLength();
    public void legCouponPaymentDate(AsciiSequenceView view);
    public byte[] legIssueDate();
    public boolean hasLegIssueDate();
    public int legIssueDateLength();
    public void legIssueDate(AsciiSequenceView view);
    public char[] legRepoCollateralSecurityType();
    public boolean hasLegRepoCollateralSecurityType();
    public int legRepoCollateralSecurityTypeLength();
    public void legRepoCollateralSecurityType(AsciiSequenceView view);
    public int legRepurchaseTerm();
    public boolean hasLegRepurchaseTerm();
    public DecimalFloat legRepurchaseRate();
    public boolean hasLegRepurchaseRate();
    public DecimalFloat legFactor();
    public boolean hasLegFactor();
    public char[] legCreditRating();
    public boolean hasLegCreditRating();
    public int legCreditRatingLength();
    public void legCreditRating(AsciiSequenceView view);
    public char[] legInstrRegistry();
    public boolean hasLegInstrRegistry();
    public int legInstrRegistryLength();
    public void legInstrRegistry(AsciiSequenceView view);
    public char[] legCountryOfIssue();
    public boolean hasLegCountryOfIssue();
    public int legCountryOfIssueLength();
    public void legCountryOfIssue(AsciiSequenceView view);
    public char[] legStateOrProvinceOfIssue();
    public boolean hasLegStateOrProvinceOfIssue();
    public int legStateOrProvinceOfIssueLength();
    public void legStateOrProvinceOfIssue(AsciiSequenceView view);
    public char[] legLocaleOfIssue();
    public boolean hasLegLocaleOfIssue();
    public int legLocaleOfIssueLength();
    public void legLocaleOfIssue(AsciiSequenceView view);
    public byte[] legRedemptionDate();
    public boolean hasLegRedemptionDate();
    public int legRedemptionDateLength();
    public void legRedemptionDate(AsciiSequenceView view);
    public DecimalFloat legStrikePrice();
    public boolean hasLegStrikePrice();
    public char[] legStrikeCurrency();
    public boolean hasLegStrikeCurrency();
    public int legStrikeCurrencyLength();
    public void legStrikeCurrency(AsciiSequenceView view);
    public char legOptAttribute();
    public boolean hasLegOptAttribute();
    public DecimalFloat legContractMultiplier();
    public boolean hasLegContractMultiplier();
    public int legContractMultiplierUnit();
    public boolean hasLegContractMultiplierUnit();
    public int legFlowScheduleType();
    public boolean hasLegFlowScheduleType();
    public char[] legUnitOfMeasure();
    public boolean hasLegUnitOfMeasure();
    public int legUnitOfMeasureLength();
    public void legUnitOfMeasure(AsciiSequenceView view);
    public DecimalFloat legUnitOfMeasureQty();
    public boolean hasLegUnitOfMeasureQty();
    public char[] legPriceUnitOfMeasure();
    public boolean hasLegPriceUnitOfMeasure();
    public int legPriceUnitOfMeasureLength();
    public void legPriceUnitOfMeasure(AsciiSequenceView view);
    public DecimalFloat legPriceUnitOfMeasureQty();
    public boolean hasLegPriceUnitOfMeasureQty();
    public char[] legTimeUnit();
    public boolean hasLegTimeUnit();
    public int legTimeUnitLength();
    public void legTimeUnit(AsciiSequenceView view);
    public int legExerciseStyle();
    public boolean hasLegExerciseStyle();
    public DecimalFloat legCouponRate();
    public boolean hasLegCouponRate();
    public char[] legSecurityExchange();
    public boolean hasLegSecurityExchange();
    public int legSecurityExchangeLength();
    public void legSecurityExchange(AsciiSequenceView view);
    public char[] legIssuer();
    public boolean hasLegIssuer();
    public int legIssuerLength();
    public void legIssuer(AsciiSequenceView view);
    public int encodedLegIssuerLen();
    public boolean hasEncodedLegIssuerLen();
    public byte[] encodedLegIssuer();
    public boolean hasEncodedLegIssuer();
    public char[] legSecurityDesc();
    public boolean hasLegSecurityDesc();
    public int legSecurityDescLength();
    public void legSecurityDesc(AsciiSequenceView view);
    public int encodedLegSecurityDescLen();
    public boolean hasEncodedLegSecurityDescLen();
    public byte[] encodedLegSecurityDesc();
    public boolean hasEncodedLegSecurityDesc();
    public DecimalFloat legRatioQty();
    public boolean hasLegRatioQty();
    public char legSide();
    public boolean hasLegSide();
    public char[] legCurrency();
    public boolean hasLegCurrency();
    public int legCurrencyLength();
    public void legCurrency(AsciiSequenceView view);
    public char[] legPool();
    public boolean hasLegPool();
    public int legPoolLength();
    public void legPool(AsciiSequenceView view);
    public byte[] legDatedDate();
    public boolean hasLegDatedDate();
    public int legDatedDateLength();
    public void legDatedDate(AsciiSequenceView view);
    public byte[] legContractSettlMonth();
    public boolean hasLegContractSettlMonth();
    public int legContractSettlMonthLength();
    public void legContractSettlMonth(AsciiSequenceView view);
    public byte[] legInterestAccrualDate();
    public boolean hasLegInterestAccrualDate();
    public int legInterestAccrualDateLength();
    public void legInterestAccrualDate(AsciiSequenceView view);
    public int legPutOrCall();
    public boolean hasLegPutOrCall();
    public DecimalFloat legOptionRatio();
    public boolean hasLegOptionRatio();
    public DecimalFloat legPrice();
    public boolean hasLegPrice();

}
